# Generated by Django 3.1.4 on 2021-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_text', models.CharField(max_length=2000)),
                ('idea_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
